apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
  namespace: default
data:
  metricbeat.yaml: |
    - module: kubernetes
      metricsets:
        - node
        - system
        - pod
        - container
        - volume
      period: 10s
      hosts: ["https://${NODE_NAME}:10250"]
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      ssl.verification_mode: "none"
      in_cluster: true
      field: kubernetes
      matchers:
        - field: "kubernetes.pod.name"
          values:
            - "${POD_NAME}"
    - module: system
      metricsets:
        - cpu
        - memory
        - network
        - process
        - process_summary
      period: 10s

