apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-depl
spec:
  selector:
    matchLabels:
      app: order-depl
  template:
    metadata:
      labels:
        app: order-depl
    spec:
      containers:
      - name: order-depl
        image: mahirminhajk/r.order
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
          - name: ELASTICSEARCH_USERNAME
            value: elastic
          - name: ELASTICSEARCH_PASSWORD
            value: changeme
          - name: REDIS_URL
            value: 'redis://redis-srv:6379'
        resources:
          limits:
            memory: "1Gi"
            cpu: "1500m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-srv
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3000'
    prometheus.io/path: '/metrics'
spec:
  selector:
    app: order-depl
  ports:
    - name: order
      protocol: TCP
      port: 3000
      targetPort: 3000