apiVersion: skaffold/v2beta3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/rabbitmq-depl.yaml
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: mahirminhajk/r.order
      context: order-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: mahirminhajk/r.payment
      context: payment-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'app/**/*.js'
            dest: .